# Generated by Django 6.0.4 on 2026-04-29 03:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_productivity', '0003_fdsparameterset_fdsanalysis_parameter_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive experiment label', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional notes about this experiment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('control_csv_path', models.CharField(blank=True, max_length=500)),
                ('genai_csv_path', models.CharField(blank=True, max_length=500)),
                ('control_total_commits', models.IntegerField(blank=True, null=True)),
                ('control_developer_count', models.IntegerField(blank=True, null=True)),
                ('control_mean_fds', models.FloatField(blank=True, null=True)),
                ('control_mean_speed_sec', models.FloatField(blank=True, help_text='Mean time between commits in seconds — lower means faster', null=True)),
                ('control_mean_churn', models.FloatField(blank=True, help_text='Mean total lines changed per developer', null=True)),
                ('genai_total_commits', models.IntegerField(blank=True, null=True)),
                ('genai_developer_count', models.IntegerField(blank=True, null=True)),
                ('genai_mean_fds', models.FloatField(blank=True, null=True)),
                ('genai_mean_speed_sec', models.FloatField(blank=True, null=True)),
                ('genai_mean_churn', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_experiments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'A/B Experiment',
                'verbose_name_plural': 'A/B Experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABDeveloperScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('control', 'Control (No AI)'), ('genai', 'GenAI (GitHub Copilot)')], max_length=10)),
                ('author_email', models.CharField(max_length=254)),
                ('fds_score', models.FloatField(default=0.0)),
                ('avg_effort', models.FloatField(default=0.0)),
                ('avg_importance', models.FloatField(default=0.0)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_churn', models.FloatField(default=0.0)),
                ('mean_speed_sec', models.FloatField(default=0.0, help_text='Mean seconds between commits — lower is faster')),
                ('speed_z_mean', models.FloatField(default=0.0)),
                ('scale_z_mean', models.FloatField(default=0.0)),
                ('reach_z_mean', models.FloatField(default=0.0)),
                ('centrality_z_mean', models.FloatField(default=0.0)),
                ('dominance_z_mean', models.FloatField(default=0.0)),
                ('novelty_z_mean', models.FloatField(default=0.0)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_scores', to='dev_productivity.abexperiment')),
            ],
            options={
                'ordering': ['group', '-fds_score'],
                'unique_together': {('experiment', 'group', 'author_email')},
            },
        ),
    ]
